version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: multi-stage.dockerfile

    expose:
      - "8090"

    networks:
      - front-networks

    environment:
      - PING_LISTEN_PORT=8090

    restart: always

    ports:
      - "8090:8090"

networks:
  front-networks:
    driver: bridge
